services:
  database:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - local
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - "database"
    networks:
      - local
    command: "npm run dev"
  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - "backend"
    networks:
      - local
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - "backend"
      - "frontend"
    networks:
      - local
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:

networks:
  local:
    driver: bridge